"""Custom icon set (generated by tools/make_icons.py)."""

import os

import bpy.utils.previews

_pcoll = None


def icon(name):
    """icon_value for a bundled icon, or 0 (no icon) if missing."""
    if _pcoll is None:
        return 0
    item = _pcoll.get(name)
    return item.icon_id if item else 0


def register():
    global _pcoll
    _pcoll = bpy.utils.previews.new()
    folder = os.path.join(os.path.dirname(__file__), "icons")
    for f in sorted(os.listdir(folder)):
        if f.endswith(".png"):
            _pcoll.load(f[:-4], os.path.join(folder, f), 'IMAGE')


def unregister():
    global _pcoll
    if _pcoll is not None:
        bpy.utils.previews.remove(_pcoll)
        _pcoll = None
